# Generated by Django 3.2 on 2021-12-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=10, unique=True, verbose_name='Booking number')),
                ('ship_arrival_date', models.DateField(verbose_name='Ship arrival date')),
                ('ship_departure_date', models.DateField(verbose_name='Ship departure date')),
            ],
            options={
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='DischargePort',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_port', models.CharField(max_length=4, unique=True, verbose_name='Code discharge port')),
                ('descriptionD_port', models.CharField(max_length=55, verbose_name='Description discharge port')),
            ],
            options={
                'verbose_name_plural': 'Discharge Port',
            },
        ),
        migrations.CreateModel(
            name='LoadingPort',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_port', models.CharField(max_length=4, unique=True, verbose_name='Code loading port')),
                ('descriptionL_port', models.CharField(max_length=55, verbose_name='Description loading Port')),
            ],
            options={
                'verbose_name_plural': 'Loading Port',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='Vehicle Identification Number')),
                ('make', models.CharField(blank=True, max_length=55, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=55, verbose_name='Model')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight')),
                ('pk_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name_plural': 'Vehicle',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discharge_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.dischargeport', verbose_name='Discharge Port'),
        ),
        migrations.AddField(
            model_name='booking',
            name='loading_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.loadingport', verbose_name='Loading Port'),
        ),
    ]
